language: node_js
os:
  - linux
  - osx
node_js:
  - ">=0.12"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"
  - "iojs-v1.0.4"
before_install:
  - sudo apt-get install fontforge
  - npm install -g grunt-cli
script: grunt test
